# Información del Proyecto
sonar.projectKey=proyecto-frontend-classroom
sonar.projectName=Proyecto FrontEnd - Classroom Module
sonar.projectVersion=1.0.0

# Rutas del código fuente
sonar.sources=src/views/Classroom,src/components/Classroom,src/context/Classroom,src/services/classroom.service.js
sonar.sourceEncoding=UTF-8

# Exclusiones
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/*.test.js,**/*.test.jsx,**/*.spec.js,**/*.spec.jsx

# Configuración de JavaScript/React
sonar.javascript.file.suffixes=.js,.jsx

# Configuración del servidor SonarQube
sonar.host.url=http://localhost:9000
sonar.token=sqp_0111b7fdd3f13f7591f7f628d7ba8a082e2cfb15
